import {
  boolean,
  date,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

export const leads = pgTable("leads", {
  id: uuid("id").defaultRandom().primaryKey(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  status: text("status", {
    enum: ["new", "verified", "credential_verified", "distributed", "sold", "rejected", "returned"],
  })
    .default("new")
    .notNull(),
  qualityScore: integer("quality_score"),
  source: text("source"),
  sourceCampaign: text("source_campaign"),
  sourceKeyword: text("source_keyword"),
  utmSource: text("utm_source"),
  utmMedium: text("utm_medium"),
  utmCampaign: text("utm_campaign"),
  utmContent: text("utm_content"),
  utmTerm: text("utm_term"),
  intakePath: text("intake_path", { enum: ["program_table", "multi_step_form"] }).notNull(),
  loanProgramType: text("loan_program_type", { enum: ["professional", "physician_doctor"] }).default("professional").notNull(),
  selectedProgramId: text("selected_program_id"),
  professionDegree: text("profession_degree", {
    enum: [
      "medical_resident",
      "md",
      "do",
      "dds",
      "dmd",
      "dpm",
      "dvm",
      "od",
      "ophthalmologist_md",
      "jd",
      "cpa",
      "pharmd",
      "pa",
      "rn",
      "np",
      "crna",
      "cns",
      "atp_pilot",
      "other",
    ],
  }).notNull(),
  professionDegreeOther: text("profession_degree_other"),
  credentialVerified: boolean("credential_verified").default(false),
  credentialVerificationSource: text("credential_verification_source"),
  credentialVerificationId: text("credential_verification_id"),
  careerStage: text("career_stage", {
    enum: [
      "resident_fellow",
      "within_1_year_training",
      "practicing_1_5",
      "practicing_5_10",
      "practicing_10_plus",
      "student_with_contract",
    ],
  }),
  residencyCompletionDate: date("residency_completion_date"),
  hasEmploymentContract: boolean("has_employment_contract"),
  yearsSinceBarAdmission: integer("years_since_bar_admission"),
  loanPurpose: text("loan_purpose", { enum: ["purchase", "refinance", "cashout_refi", "heloc"] }).notNull(),
  propertyType: text("property_type", { enum: ["single_family", "condo_townhome", "multi_family"] }),
  propertyUse: text("property_use", { enum: ["primary", "second_home", "investment"] }),
  propertyZip: text("property_zip").notNull(),
  propertyState: text("property_state"),
  propertyCity: text("property_city"),
  purchasePrice: integer("purchase_price"),
  downPayment: integer("down_payment"),
  downPaymentPercent: numeric("down_payment_percent"),
  currentMortgageBalance: integer("current_mortgage_balance"),
  estimatedHomeValue: integer("estimated_home_value"),
  creditScoreRange: text("credit_score_range", {
    enum: ["excellent_740_plus", "good_680_739", "fair_620_679", "below_620", "not_sure"],
  }),
  timeline: text("timeline", { enum: ["asap", "30_days", "1_3_months", "3_6_months", "researching"] }),
  studentLoanBalanceRange: text("student_loan_balance_range", {
    enum: ["none", "under_100k", "100_200k", "200_400k", "over_400k"],
  }),
  studentLoanMonthlyPaymentRange: text("student_loan_monthly_payment_range", {
    enum: ["zero_deferred", "under_500", "500_1500", "1500_3000", "over_3000"],
  }),
  onIdrPlan: text("on_idr_plan", { enum: ["yes", "no", "not_sure"] }),
  employmentStatus: text("employment_status", {
    enum: ["employed_w2", "self_employed", "contractor_1099", "new_position_contract", "resident_fellow", "not_employed"],
  }),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  phoneType: text("phone_type", { enum: ["mobile", "landline", "voip", "unknown"] }),
  ipAddress: text("ip_address"),
  ipFraudScore: integer("ip_fraud_score"),
  ipGeolocationState: text("ip_geolocation_state"),
  userAgent: text("user_agent"),
  recaptchaScore: numeric("recaptcha_score"),
  trustedformCertUrl: text("trustedform_cert_url"),
  jornayaLeadidToken: text("jornaya_leadid_token"),
  isDuplicate: boolean("is_duplicate").default(false),
  duplicateOfLeadId: uuid("duplicate_of_lead_id"),
  matchedProgramCount: integer("matched_program_count"),
  soldAt: timestamp("sold_at", { withTimezone: true }),
  totalRevenue: numeric("total_revenue"),
});

export const buyers = pgTable("buyers", {
  id: uuid("id").defaultRandom().primaryKey(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  companyName: text("company_name").notNull(),
  contactName: text("contact_name"),
  contactEmail: text("contact_email"),
  contactPhone: text("contact_phone"),
  buyerType: text("buyer_type", { enum: ["direct_lender", "credit_union", "aggregator", "broker"] }),
  licensedStates: jsonb("licensed_states").$type<string[]>().default([]),
  acceptedDegrees: jsonb("accepted_degrees").$type<string[]>().default([]),
  acceptsResidents: boolean("accepts_residents").default(true),
  yearsFromTrainingMax: integer("years_from_training_max"),
  maxLoanAmount: integer("max_loan_amount"),
  acceptedLoanTypes: jsonb("accepted_loan_types").$type<string[]>().default([]),
  minCreditTier: text("min_credit_tier"),
  maxLeadsPerDay: integer("max_leads_per_day"),
  maxLeadsPerMonth: integer("max_leads_per_month"),
  leadsPurchasedToday: integer("leads_purchased_today").default(0),
  leadsPurchasedThisMonth: integer("leads_purchased_this_month").default(0),
  pricePerLeadExclusive: numeric("price_per_lead_exclusive"),
  pricePerLeadShared: numeric("price_per_lead_shared"),
  credentialVerifiedPremium: numeric("credential_verified_premium"),
  pingPostEndpointUrl: text("ping_post_endpoint_url"),
  apiKey: text("api_key"),
  status: text("status", { enum: ["active", "paused", "onboarding", "churned"] }).default("onboarding"),
  requiresTrustedform: boolean("requires_trustedform").default(false),
  requiresJornaya: boolean("requires_jornaya").default(false),
  acceptsVoip: boolean("accepts_voip").default(true),
  notes: text("notes"),
});

export const leadDistributionLog = pgTable("lead_distribution_log", {
  id: uuid("id").defaultRandom().primaryKey(),
  leadId: uuid("lead_id")
    .references(() => leads.id)
    .notNull(),
  buyerId: uuid("buyer_id")
    .references(() => buyers.id)
    .notNull(),
  pingSentAt: timestamp("ping_sent_at", { withTimezone: true }),
  pingResponse: text("ping_response", { enum: ["accepted", "rejected", "no_response", "error"] }),
  pingBidPrice: numeric("ping_bid_price"),
  postSentAt: timestamp("post_sent_at", { withTimezone: true }),
  postAccepted: boolean("post_accepted"),
  soldPrice: numeric("sold_price"),
  rejectionReason: text("rejection_reason"),
  returned: boolean("returned").default(false),
  returnReason: text("return_reason"),
  returnDate: timestamp("return_date", { withTimezone: true }),
});

export const lenderPrograms = pgTable("lender_programs", {
  id: uuid("id").defaultRandom().primaryKey(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  programType: text("program_type", { enum: ["professional", "physician_doctor"] }).default("professional").notNull(),
  lenderName: text("lender_name").notNull(),
  programName: text("program_name"),
  acceptedDegrees: jsonb("accepted_degrees").$type<string[]>().default([]),
  acceptsResidents: boolean("accepts_residents").default(true),
  yearsFromTrainingMax: integer("years_from_training_max"),
  maxLoanAmountZeroDown: integer("max_loan_amount_zero_down"),
  maxLoanAmount5Down: integer("max_loan_amount_5_down"),
  maxLoanAmount10Down: integer("max_loan_amount_10_down"),
  maxLoanAmountTotal: integer("max_loan_amount_total"),
  pmiRequired: boolean("pmi_required").default(false),
  rateTypesAvailable: jsonb("rate_types_available").$type<string[]>().default([]),
  studentLoanTreatment: text("student_loan_treatment", { enum: ["excluded", "ibr_payment", "full_payment", "varies"] }),
  licensedStates: jsonb("licensed_states").$type<string[]>().default([]),
  requiresEmploymentContract: boolean("requires_employment_contract").default(false),
  contractStartWindowDays: integer("contract_start_window_days"),
  refinanceAvailable: boolean("refinance_available").default(false),
  cashOutAvailable: boolean("cash_out_available").default(false),
  fixedRateEstimate: numeric("fixed_rate_estimate"),
  armRateEstimate: numeric("arm_rate_estimate"),
  rateLastUpdated: date("rate_last_updated"),
  lenderWebsiteUrl: text("lender_website_url"),
  programNotes: text("program_notes"),
  isActive: boolean("is_active").default(true),
  lastVerified: date("last_verified"),
  displayOrder: integer("display_order").default(0),
});

export const mortgageRateSources = pgTable("mortgage_rate_sources", {
  id: uuid("id").defaultRandom().primaryKey(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  programSlug: text("program_slug").notNull(),
  lenderName: text("lender_name").notNull(),
  programName: text("program_name"),
  programType: text("program_type", { enum: ["professional", "physician_doctor"] }).notNull(),
  sourceUrl: text("source_url").notNull(),
  scrapeMethod: text("scrape_method", { enum: ["fetch_html", "browser"] }).default("fetch_html").notNull(),
  selectorHints: jsonb("selector_hints").$type<Record<string, unknown>>().default({}),
  notes: text("notes"),
  isActive: boolean("is_active").default(true).notNull(),
});

export const mortgageRateScrapeRuns = pgTable("mortgage_rate_scrape_runs", {
  id: uuid("id").defaultRandom().primaryKey(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  trigger: text("trigger", { enum: ["manual", "schedule_10am", "schedule_3pm"] }).default("manual").notNull(),
  mode: text("mode", { enum: ["fetch_html", "browser"] }).default("fetch_html").notNull(),
  status: text("status", { enum: ["running", "success", "partial", "error"] }).default("running").notNull(),
  totalSources: integer("total_sources").default(0).notNull(),
  successfulSources: integer("successful_sources").default(0).notNull(),
  failedSources: integer("failed_sources").default(0).notNull(),
  notes: text("notes"),
});

export const mortgageRateSnapshots = pgTable("mortgage_rate_snapshots", {
  id: uuid("id").defaultRandom().primaryKey(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  runId: uuid("run_id").references(() => mortgageRateScrapeRuns.id),
  sourceId: uuid("source_id").references(() => mortgageRateSources.id),
  scrapedAt: timestamp("scraped_at", { withTimezone: true }).defaultNow().notNull(),
  programSlug: text("program_slug").notNull(),
  lenderName: text("lender_name").notNull(),
  programName: text("program_name"),
  programType: text("program_type", { enum: ["professional", "physician_doctor"] }).notNull(),
  sourceUrl: text("source_url").notNull(),
  loanProduct: text("loan_product"),
  interestRate: numeric("interest_rate"),
  apr: numeric("apr"),
  points: numeric("points"),
  monthlyPayment: integer("monthly_payment"),
  closingFees: integer("closing_fees"),
  lenderFees: integer("lender_fees"),
  thirdPartyFees: integer("third_party_fees"),
  status: text("status", { enum: ["success", "no_rate_found", "blocked", "error"] }).notNull(),
  confidence: numeric("confidence"),
  rawText: text("raw_text"),
  errorMessage: text("error_message"),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}),
});

export const financialTransactions = pgTable("financial_transactions", {
  id: uuid("id").defaultRandom().primaryKey(),
  leadId: uuid("lead_id").references(() => leads.id),
  buyerId: uuid("buyer_id").references(() => buyers.id),
  transactionType: text("transaction_type", { enum: ["sale", "return_credit", "adjustment"] }).notNull(),
  amount: numeric("amount").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  notes: text("notes"),
});

export const formEvents = pgTable("form_events", {
  id: uuid("id").defaultRandom().primaryKey(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  eventName: text("event_name").notNull(),
  step: integer("step"),
  sessionId: text("session_id"),
  payload: jsonb("payload").$type<Record<string, unknown>>().default({}),
});
