import type { BuyerRecord, LeadRecord } from "@/lib/types";

export const mockLeads: LeadRecord[] = [
  {
    id: "lead-demo-1",
    createdAt: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
    status: "credential_verified",
    qualityScore: 82,
    source: "seo",
    utmSource: "google",
    utmMedium: "organic",
    intakePath: "multi_step_form",
    loanProgramType: "physician_doctor",
    professionDegree: "md",
    careerStage: "within_1_year_training",
    credentialVerified: true,
    credentialVerificationSource: "nppes",
    credentialVerificationId: "1234567890",
    loanPurpose: "purchase",
    propertyZip: "60611",
    propertyState: "IL",
    propertyCity: "Chicago",
    purchasePrice: 875000,
    downPayment: 0,
    creditScoreRange: "excellent_740_plus",
    timeline: "30_days",
    studentLoanBalanceRange: "200_400k",
    studentLoanMonthlyPaymentRange: "500_1500",
    onIdrPlan: "yes",
    employmentStatus: "new_position_contract",
    hasEmploymentContract: true,
    firstName: "Maya",
    lastName: "Patel",
    email: "maya.patel@example.com",
    phone: "(312) 555-0144",
    phoneType: "mobile",
    ipFraudScore: 7,
    matchedProgramCount: 6,
    totalRevenue: 175,
  },
  {
    id: "lead-demo-2",
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    status: "new",
    qualityScore: 63,
    source: "google_ads",
    utmSource: "google",
    utmMedium: "cpc",
    utmCampaign: "dentist-loans",
    intakePath: "program_table",
    loanProgramType: "physician_doctor",
    selectedProgramId: "fifth-third-doctor-dentist",
    professionDegree: "dds",
    careerStage: "practicing_1_5",
    credentialVerified: false,
    loanPurpose: "purchase",
    propertyZip: "33131",
    propertyState: "FL",
    propertyCity: "Miami",
    purchasePrice: 720000,
    creditScoreRange: "good_680_739",
    timeline: "1_3_months",
    employmentStatus: "self_employed",
    firstName: "Evan",
    lastName: "Cohen",
    email: "evan.cohen@example.com",
    phone: "(305) 555-0192",
    phoneType: "unknown",
    matchedProgramCount: 4,
    totalRevenue: null,
  },
  {
    id: "lead-demo-3",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    status: "sold",
    qualityScore: 74,
    source: "affiliate",
    utmSource: "bar_association",
    utmMedium: "partner",
    intakePath: "multi_step_form",
    loanProgramType: "professional",
    professionDegree: "jd",
    careerStage: "practicing_5_10",
    credentialVerified: false,
    credentialVerificationSource: "state_bar_stub",
    loanPurpose: "refinance",
    propertyZip: "10011",
    propertyState: "NY",
    propertyCity: "New York",
    estimatedHomeValue: 1200000,
    currentMortgageBalance: 820000,
    creditScoreRange: "excellent_740_plus",
    timeline: "asap",
    employmentStatus: "employed_w2",
    firstName: "Rachel",
    lastName: "Morgan",
    email: "rachel.morgan@example.com",
    phone: "(212) 555-0168",
    phoneType: "mobile",
    matchedProgramCount: 3,
    totalRevenue: 240,
  },
];

export const mockBuyers: BuyerRecord[] = [
  {
    id: "buyer-1",
    companyName: "Summit Physician Lending",
    contactName: "Jordan Mills",
    contactEmail: "partners@summitlending.example",
    contactPhone: "(800) 555-0131",
    buyerType: "direct_lender",
    licensedStates: ["IL", "IN", "MI", "OH", "WI"],
    acceptedDegrees: ["md", "do", "dds", "dmd"],
    acceptsResidents: true,
    maxLeadsPerDay: 40,
    maxLeadsPerMonth: 700,
    leadsPurchasedToday: 12,
    leadsPurchasedThisMonth: 244,
    pricePerLeadExclusive: 185,
    pricePerLeadShared: 75,
    status: "active",
    requiresTrustedform: true,
    requiresJornaya: false,
    acceptsVoip: false,
  },
  {
    id: "buyer-2",
    companyName: "Counsel Home Finance",
    contactName: "Priya Shah",
    contactEmail: "ops@counselhome.example",
    contactPhone: "(888) 555-0180",
    buyerType: "broker",
    licensedStates: ["NY", "NJ", "CT", "MA", "PA"],
    acceptedDegrees: ["jd", "cpa"],
    acceptsResidents: false,
    maxLeadsPerDay: 20,
    maxLeadsPerMonth: 350,
    leadsPurchasedToday: 4,
    leadsPurchasedThisMonth: 89,
    pricePerLeadExclusive: 160,
    pricePerLeadShared: 60,
    status: "active",
    requiresTrustedform: false,
    requiresJornaya: false,
    acceptsVoip: true,
  },
];
