import type { LenderProgram } from "@/lib/types";
import { PHYSICIAN_DOCTOR_LOAN_DEGREES, PROFESSIONAL_LOAN_DEGREES } from "@/lib/constants/professions";
import { STATE_CODES } from "@/lib/constants/states";

const regional = (codes: string[]) => codes;

export const LENDER_PROGRAMS: LenderProgram[] = [
  {
    id: "fifth-third-doctor-dentist",
    programType: "physician_doctor",
    lenderName: "Fifth Third Bank",
    programName: "Doctor and Dentist Mortgage",
    acceptedDegrees: PHYSICIAN_DOCTOR_LOAN_DEGREES,
    acceptsResidents: true,
    yearsFromTrainingMax: null,
    maxLoanAmountZeroDown: 1000000,
    maxLoanAmount5Down: 1500000,
    maxLoanAmount10Down: 2000000,
    maxLoanAmountTotal: 2000000,
    pmiRequired: false,
    rateTypesAvailable: ["Fixed", "ARM 5/1", "ARM 7/1"],
    studentLoanTreatment: "varies",
    licensedStates: regional(["FL", "IL", "IN", "KY", "MI", "OH", "TN", "WV", "GA", "NC", "SC", "WI", "PA"]),
    requiresEmploymentContract: false,
    refinanceAvailable: true,
    cashOutAvailable: false,
    fixedRateEstimate: null,
    armRateEstimate: null,
    lenderWebsiteUrl: "https://www.53.com/",
    programNotes: "Available to physicians, dentists, and veterinarians with no PMI and resident-friendly underwriting.",
    isActive: true,
    displayOrder: 1,
    lastVerified: "2026-06-01",
  },
  {
    id: "keybank-professional",
    programType: "professional",
    lenderName: "KeyBank",
    programName: "Professional Mortgage",
    acceptedDegrees: PROFESSIONAL_LOAN_DEGREES,
    acceptsResidents: true,
    yearsFromTrainingMax: null,
    maxLoanAmountZeroDown: 1000000,
    maxLoanAmount5Down: 1500000,
    maxLoanAmount10Down: 3500000,
    maxLoanAmountTotal: 3500000,
    pmiRequired: false,
    rateTypesAvailable: ["Fixed", "ARM 7/1", "ARM 10/1"],
    studentLoanTreatment: "ibr_payment",
    licensedStates: STATE_CODES as string[],
    requiresEmploymentContract: false,
    refinanceAvailable: true,
    cashOutAvailable: true,
    fixedRateEstimate: null,
    armRateEstimate: null,
    lenderWebsiteUrl: "https://www.key.com/",
    programNotes: "Broad professional eligibility; administrators should confirm state-by-state overlays before publishing.",
    isActive: true,
    displayOrder: 2,
    lastVerified: "2026-06-01",
  },
  {
    id: "truist-doctor-loan",
    programType: "physician_doctor",
    lenderName: "Truist",
    programName: "Doctor Loan",
    acceptedDegrees: PHYSICIAN_DOCTOR_LOAN_DEGREES,
    acceptsResidents: true,
    yearsFromTrainingMax: 10,
    maxLoanAmountZeroDown: 1000000,
    maxLoanAmount5Down: 1500000,
    maxLoanAmount10Down: 2000000,
    maxLoanAmountTotal: 2000000,
    pmiRequired: false,
    rateTypesAvailable: ["Fixed", "ARM 5/1", "ARM 7/1", "ARM 10/1"],
    studentLoanTreatment: "ibr_payment",
    licensedStates: regional(["AL", "AR", "DC", "FL", "GA", "IN", "KY", "MD", "MS", "NC", "NJ", "OH", "PA", "SC", "TN", "TX", "VA", "WV"]),
    requiresEmploymentContract: false,
    refinanceAvailable: true,
    cashOutAvailable: false,
    fixedRateEstimate: null,
    armRateEstimate: null,
    lenderWebsiteUrl: "https://www.truist.com/",
    programNotes: "Southeast-forward program with 100% financing tiers for eligible doctors.",
    isActive: true,
    displayOrder: 3,
    lastVerified: "2026-06-01",
  },
  {
    id: "first-horizon-medical",
    programType: "physician_doctor",
    lenderName: "First Horizon",
    programName: "Medical Professional Mortgage",
    acceptedDegrees: PHYSICIAN_DOCTOR_LOAN_DEGREES,
    acceptsResidents: false,
    yearsFromTrainingMax: null,
    maxLoanAmountZeroDown: null,
    maxLoanAmount5Down: 1500000,
    maxLoanAmount10Down: 2500000,
    maxLoanAmountTotal: 2500000,
    pmiRequired: false,
    rateTypesAvailable: ["Fixed", "ARM 7/1", "ARM 10/1"],
    studentLoanTreatment: "varies",
    licensedStates: regional(["AK", "AR", "CT", "GA", "FL", "LA", "MS", "NC", "SC", "TN", "TX", "VA", "NJ", "NY"]),
    requiresEmploymentContract: true,
    refinanceAvailable: true,
    cashOutAvailable: false,
    fixedRateEstimate: null,
    armRateEstimate: null,
    lenderWebsiteUrl: "https://www.firsthorizon.com/",
    programNotes: "Designed for practicing medical and dental professionals; residents not accepted.",
    isActive: true,
    displayOrder: 4,
    lastVerified: "2026-06-01",
  },
  {
    id: "citizens-professional",
    programType: "professional",
    lenderName: "Citizens Bank",
    programName: "Professional Mortgage",
    acceptedDegrees: PROFESSIONAL_LOAN_DEGREES,
    acceptsResidents: true,
    yearsFromTrainingMax: 10,
    maxLoanAmountZeroDown: 850000,
    maxLoanAmount5Down: 1250000,
    maxLoanAmount10Down: 2000000,
    maxLoanAmountTotal: 2000000,
    pmiRequired: false,
    rateTypesAvailable: ["Fixed", "ARM 7/1"],
    studentLoanTreatment: "ibr_payment",
    licensedStates: regional(["CT", "DE", "FL", "MA", "MD", "MI", "NH", "NJ", "NY", "OH", "PA", "RI", "VA", "VT"]),
    requiresEmploymentContract: false,
    refinanceAvailable: true,
    cashOutAvailable: false,
    fixedRateEstimate: null,
    armRateEstimate: null,
    lenderWebsiteUrl: "https://www.citizensbank.com/",
    programNotes: "Northeast and expanding footprint with professional-degree underwriting.",
    isActive: true,
    displayOrder: 5,
    lastVerified: "2026-06-01",
  },
  {
    id: "td-bank-medical",
    programType: "physician_doctor",
    lenderName: "TD Bank",
    programName: "Medical Professional Mortgage",
    acceptedDegrees: PHYSICIAN_DOCTOR_LOAN_DEGREES,
    acceptsResidents: true,
    yearsFromTrainingMax: 10,
    maxLoanAmountZeroDown: 750000,
    maxLoanAmount5Down: 1250000,
    maxLoanAmount10Down: 1500000,
    maxLoanAmountTotal: 1500000,
    pmiRequired: false,
    rateTypesAvailable: ["Fixed", "ARM 5/1", "ARM 7/1"],
    studentLoanTreatment: "varies",
    licensedStates: regional(["CT", "DE", "FL", "ME", "MD", "MA", "NH", "NJ", "NY", "NC", "PA", "RI", "SC", "VT", "VA", "DC"]),
    requiresEmploymentContract: false,
    refinanceAvailable: true,
    cashOutAvailable: false,
    fixedRateEstimate: null,
    armRateEstimate: null,
    lenderWebsiteUrl: "https://www.td.com/",
    programNotes: "East Coast medical professional option with no PMI.",
    isActive: true,
    displayOrder: 6,
    lastVerified: "2026-06-01",
  },
  {
    id: "pnc-medical-professional",
    programType: "physician_doctor",
    lenderName: "PNC Bank",
    programName: "Medical Professional Mortgage",
    acceptedDegrees: PHYSICIAN_DOCTOR_LOAN_DEGREES,
    acceptsResidents: true,
    yearsFromTrainingMax: 10,
    maxLoanAmountZeroDown: 1000000,
    maxLoanAmount5Down: 1500000,
    maxLoanAmount10Down: 2000000,
    maxLoanAmountTotal: 2000000,
    pmiRequired: false,
    rateTypesAvailable: ["Fixed", "ARM 7/1", "ARM 10/1"],
    studentLoanTreatment: "ibr_payment",
    licensedStates: STATE_CODES as string[],
    requiresEmploymentContract: false,
    refinanceAvailable: true,
    cashOutAvailable: false,
    fixedRateEstimate: null,
    armRateEstimate: null,
    lenderWebsiteUrl: "https://www.pnc.com/",
    programNotes: "National footprint; administrators should verify local availability and current overlays.",
    isActive: true,
    displayOrder: 7,
    lastVerified: "2026-06-01",
  },
  {
    id: "flagstar-professional",
    programType: "professional",
    lenderName: "Flagstar Bank",
    programName: "Professional Loan",
    acceptedDegrees: PROFESSIONAL_LOAN_DEGREES,
    acceptsResidents: true,
    yearsFromTrainingMax: 10,
    maxLoanAmountZeroDown: 1000000,
    maxLoanAmount5Down: 2000000,
    maxLoanAmount10Down: 3000000,
    maxLoanAmountTotal: 3000000,
    pmiRequired: false,
    rateTypesAvailable: ["Fixed", "ARM 5/1", "ARM 7/1"],
    studentLoanTreatment: "varies",
    licensedStates: STATE_CODES as string[],
    requiresEmploymentContract: false,
    refinanceAvailable: true,
    cashOutAvailable: true,
    fixedRateEstimate: null,
    armRateEstimate: null,
    lenderWebsiteUrl: "https://www.flagstar.com/",
    programNotes: "Professional program for borrowers within 10 years of entering profession.",
    isActive: true,
    displayOrder: 8,
    lastVerified: "2026-06-01",
  },
  {
    id: "bmo-medical",
    programType: "physician_doctor",
    lenderName: "BMO",
    programName: "Medical Professional Mortgage",
    acceptedDegrees: PHYSICIAN_DOCTOR_LOAN_DEGREES,
    acceptsResidents: true,
    yearsFromTrainingMax: null,
    maxLoanAmountZeroDown: 1000000,
    maxLoanAmount5Down: 1500000,
    maxLoanAmount10Down: 2000000,
    maxLoanAmountTotal: 2000000,
    pmiRequired: false,
    rateTypesAvailable: ["Fixed", "ARM 7/1"],
    studentLoanTreatment: "ibr_payment",
    licensedStates: regional(["AZ", "CA", "CO", "FL", "IL", "IN", "KS", "MN", "MO", "WI"]),
    requiresEmploymentContract: false,
    refinanceAvailable: true,
    cashOutAvailable: false,
    fixedRateEstimate: null,
    armRateEstimate: null,
    lenderWebsiteUrl: "https://www.bmo.com/",
    programNotes: "Upper Midwest and national-market medical professional footprint.",
    isActive: true,
    displayOrder: 9,
    lastVerified: "2026-06-01",
  },
  {
    id: "northwest-bank-physician",
    programType: "physician_doctor",
    lenderName: "Northwest Bank",
    programName: "Physician Mortgage",
    acceptedDegrees: PHYSICIAN_DOCTOR_LOAN_DEGREES,
    acceptsResidents: true,
    yearsFromTrainingMax: 10,
    maxLoanAmountZeroDown: 750000,
    maxLoanAmount5Down: 1000000,
    maxLoanAmount10Down: 1500000,
    maxLoanAmountTotal: 1500000,
    pmiRequired: false,
    rateTypesAvailable: ["Fixed", "ARM 5/1"],
    studentLoanTreatment: "varies",
    licensedStates: regional(["NY", "OH", "PA", "IN", "MD", "MI", "NJ", "VA"]),
    requiresEmploymentContract: false,
    refinanceAvailable: true,
    cashOutAvailable: false,
    fixedRateEstimate: null,
    armRateEstimate: null,
    lenderWebsiteUrl: "https://www.northwest.bank/",
    programNotes: "Mid-Atlantic physician mortgage program.",
    isActive: true,
    displayOrder: 10,
    lastVerified: "2026-06-01",
  },
  {
    id: "old-national-medical",
    programType: "physician_doctor",
    lenderName: "Old National Bank",
    programName: "Medical Professional Mortgage",
    acceptedDegrees: PHYSICIAN_DOCTOR_LOAN_DEGREES,
    acceptsResidents: true,
    yearsFromTrainingMax: 10,
    maxLoanAmountZeroDown: 750000,
    maxLoanAmount5Down: 1250000,
    maxLoanAmount10Down: 2000000,
    maxLoanAmountTotal: 2000000,
    pmiRequired: false,
    rateTypesAvailable: ["Fixed", "ARM 7/1"],
    studentLoanTreatment: "ibr_payment",
    licensedStates: regional(["AL", "FL", "GA", "IN", "KY", "MD", "NC", "NJ", "OH", "PA", "SC", "TN", "TX", "VA", "WV"]),
    requiresEmploymentContract: false,
    refinanceAvailable: true,
    cashOutAvailable: false,
    fixedRateEstimate: null,
    armRateEstimate: null,
    lenderWebsiteUrl: "https://www.oldnational.com/",
    programNotes: "Regional bank option with physician and dental eligibility.",
    isActive: true,
    displayOrder: 11,
    lastVerified: "2026-06-01",
  },
  {
    id: "arvest-physician",
    programType: "physician_doctor",
    lenderName: "Arvest Bank",
    programName: "Physician Loan",
    acceptedDegrees: PHYSICIAN_DOCTOR_LOAN_DEGREES,
    acceptsResidents: true,
    yearsFromTrainingMax: 10,
    maxLoanAmountZeroDown: 750000,
    maxLoanAmount5Down: 1000000,
    maxLoanAmount10Down: 1500000,
    maxLoanAmountTotal: 1500000,
    pmiRequired: false,
    rateTypesAvailable: ["Fixed", "ARM 5/1", "ARM 7/1"],
    studentLoanTreatment: "varies",
    licensedStates: regional(["AR", "KS", "MO", "OK"]),
    requiresEmploymentContract: false,
    refinanceAvailable: true,
    cashOutAvailable: false,
    fixedRateEstimate: null,
    armRateEstimate: null,
    lenderWebsiteUrl: "https://www.arvest.com/",
    programNotes: "Regional physician program with financing structures advertised up to 103% for eligible borrowers.",
    isActive: true,
    displayOrder: 12,
    lastVerified: "2026-06-01",
  },
];
