CREATE TABLE "buyers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"company_name" text NOT NULL,
	"contact_name" text,
	"contact_email" text,
	"contact_phone" text,
	"buyer_type" text,
	"licensed_states" jsonb DEFAULT '[]'::jsonb,
	"accepted_degrees" jsonb DEFAULT '[]'::jsonb,
	"accepts_residents" boolean DEFAULT true,
	"years_from_training_max" integer,
	"max_loan_amount" integer,
	"accepted_loan_types" jsonb DEFAULT '[]'::jsonb,
	"min_credit_tier" text,
	"max_leads_per_day" integer,
	"max_leads_per_month" integer,
	"leads_purchased_today" integer DEFAULT 0,
	"leads_purchased_this_month" integer DEFAULT 0,
	"price_per_lead_exclusive" numeric,
	"price_per_lead_shared" numeric,
	"credential_verified_premium" numeric,
	"ping_post_endpoint_url" text,
	"api_key" text,
	"status" text DEFAULT 'onboarding',
	"requires_trustedform" boolean DEFAULT false,
	"requires_jornaya" boolean DEFAULT false,
	"accepts_voip" boolean DEFAULT true,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "financial_transactions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"lead_id" uuid,
	"buyer_id" uuid,
	"transaction_type" text NOT NULL,
	"amount" numeric NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "form_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"event_name" text NOT NULL,
	"step" integer,
	"session_id" text,
	"payload" jsonb DEFAULT '{}'::jsonb
);
--> statement-breakpoint
CREATE TABLE "lead_distribution_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"lead_id" uuid NOT NULL,
	"buyer_id" uuid NOT NULL,
	"ping_sent_at" timestamp with time zone,
	"ping_response" text,
	"ping_bid_price" numeric,
	"post_sent_at" timestamp with time zone,
	"post_accepted" boolean,
	"sold_price" numeric,
	"rejection_reason" text,
	"returned" boolean DEFAULT false,
	"return_reason" text,
	"return_date" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "leads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"status" text DEFAULT 'new' NOT NULL,
	"quality_score" integer,
	"source" text,
	"source_campaign" text,
	"source_keyword" text,
	"utm_source" text,
	"utm_medium" text,
	"utm_campaign" text,
	"utm_content" text,
	"utm_term" text,
	"intake_path" text NOT NULL,
	"loan_program_type" text DEFAULT 'professional' NOT NULL,
	"selected_program_id" text,
	"profession_degree" text NOT NULL,
	"profession_degree_other" text,
	"credential_verified" boolean DEFAULT false,
	"credential_verification_source" text,
	"credential_verification_id" text,
	"career_stage" text,
	"residency_completion_date" date,
	"has_employment_contract" boolean,
	"years_since_bar_admission" integer,
	"loan_purpose" text NOT NULL,
	"property_type" text,
	"property_use" text,
	"property_zip" text NOT NULL,
	"property_state" text,
	"property_city" text,
	"purchase_price" integer,
	"down_payment" integer,
	"down_payment_percent" numeric,
	"current_mortgage_balance" integer,
	"estimated_home_value" integer,
	"credit_score_range" text,
	"timeline" text,
	"student_loan_balance_range" text,
	"student_loan_monthly_payment_range" text,
	"on_idr_plan" text,
	"employment_status" text,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text NOT NULL,
	"phone_type" text,
	"ip_address" text,
	"ip_fraud_score" integer,
	"ip_geolocation_state" text,
	"user_agent" text,
	"recaptcha_score" numeric,
	"trustedform_cert_url" text,
	"jornaya_leadid_token" text,
	"is_duplicate" boolean DEFAULT false,
	"duplicate_of_lead_id" uuid,
	"matched_program_count" integer,
	"sold_at" timestamp with time zone,
	"total_revenue" numeric
);
--> statement-breakpoint
CREATE TABLE "lender_programs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"program_type" text DEFAULT 'professional' NOT NULL,
	"lender_name" text NOT NULL,
	"program_name" text,
	"accepted_degrees" jsonb DEFAULT '[]'::jsonb,
	"accepts_residents" boolean DEFAULT true,
	"years_from_training_max" integer,
	"max_loan_amount_zero_down" integer,
	"max_loan_amount_5_down" integer,
	"max_loan_amount_10_down" integer,
	"max_loan_amount_total" integer,
	"pmi_required" boolean DEFAULT false,
	"rate_types_available" jsonb DEFAULT '[]'::jsonb,
	"student_loan_treatment" text,
	"licensed_states" jsonb DEFAULT '[]'::jsonb,
	"requires_employment_contract" boolean DEFAULT false,
	"contract_start_window_days" integer,
	"refinance_available" boolean DEFAULT false,
	"cash_out_available" boolean DEFAULT false,
	"fixed_rate_estimate" numeric,
	"arm_rate_estimate" numeric,
	"rate_last_updated" date,
	"lender_website_url" text,
	"program_notes" text,
	"is_active" boolean DEFAULT true,
	"last_verified" date,
	"display_order" integer DEFAULT 0
);
--> statement-breakpoint
CREATE TABLE "mortgage_rate_scrape_runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone,
	"trigger" text DEFAULT 'manual' NOT NULL,
	"mode" text DEFAULT 'fetch_html' NOT NULL,
	"status" text DEFAULT 'running' NOT NULL,
	"total_sources" integer DEFAULT 0 NOT NULL,
	"successful_sources" integer DEFAULT 0 NOT NULL,
	"failed_sources" integer DEFAULT 0 NOT NULL,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "mortgage_rate_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"run_id" uuid,
	"source_id" uuid,
	"scraped_at" timestamp with time zone DEFAULT now() NOT NULL,
	"program_slug" text NOT NULL,
	"lender_name" text NOT NULL,
	"program_name" text,
	"program_type" text NOT NULL,
	"source_url" text NOT NULL,
	"loan_product" text,
	"interest_rate" numeric,
	"apr" numeric,
	"points" numeric,
	"monthly_payment" integer,
	"closing_fees" integer,
	"lender_fees" integer,
	"third_party_fees" integer,
	"status" text NOT NULL,
	"confidence" numeric,
	"raw_text" text,
	"error_message" text,
	"metadata" jsonb DEFAULT '{}'::jsonb
);
--> statement-breakpoint
CREATE TABLE "mortgage_rate_sources" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"program_slug" text NOT NULL,
	"lender_name" text NOT NULL,
	"program_name" text,
	"program_type" text NOT NULL,
	"source_url" text NOT NULL,
	"scrape_method" text DEFAULT 'fetch_html' NOT NULL,
	"selector_hints" jsonb DEFAULT '{}'::jsonb,
	"notes" text,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
ALTER TABLE "financial_transactions" ADD CONSTRAINT "financial_transactions_lead_id_leads_id_fk" FOREIGN KEY ("lead_id") REFERENCES "public"."leads"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "financial_transactions" ADD CONSTRAINT "financial_transactions_buyer_id_buyers_id_fk" FOREIGN KEY ("buyer_id") REFERENCES "public"."buyers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lead_distribution_log" ADD CONSTRAINT "lead_distribution_log_lead_id_leads_id_fk" FOREIGN KEY ("lead_id") REFERENCES "public"."leads"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lead_distribution_log" ADD CONSTRAINT "lead_distribution_log_buyer_id_buyers_id_fk" FOREIGN KEY ("buyer_id") REFERENCES "public"."buyers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mortgage_rate_snapshots" ADD CONSTRAINT "mortgage_rate_snapshots_run_id_mortgage_rate_scrape_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."mortgage_rate_scrape_runs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mortgage_rate_snapshots" ADD CONSTRAINT "mortgage_rate_snapshots_source_id_mortgage_rate_sources_id_fk" FOREIGN KEY ("source_id") REFERENCES "public"."mortgage_rate_sources"("id") ON DELETE no action ON UPDATE no action;